name: compile

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  compile:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build