name: Build & Push Docker Image to container image registry

on:
  workflow_call:
    inputs:
      ADD_FLAVOR:
        description: "Whether to add flavor (only -dev atm) to the image tag"
        type: boolean
        required: false
        default: true
      NO_CACHE:
        description: "Whether to use build cache"
        type: boolean
        required: false
        default: false
      SCOPE:
        description: "Scope of the image (e.g. 'bot')"
        type: string
        required: true
      VERSION:
        description: "Version of the image (e.g. 'v1.0.0')"
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scope: ${{ fromJson(inputs.SCOPE) }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 2

      #- name: Set up QEMU (We don't need QEMU, because we don't build images for platforms other than linux/amd64, which is our current native arch in our infra
      #  uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract flavor
        id: flavor
        if: ${{ inputs.ADD_FLAVOR == true }}
        run: if [ "${{ github.event_name }}" = "release" ]; then echo ::set-output name=name::; else echo ::set-output name=name::-dev; fi

      - name: Generate Docker image metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: img_meta
        with:
          flavor: |
            latest=auto
            suffix=${{ steps.flavor.outputs.name }}
          images: ghcr.io/nezuchan/${{ matrix.scope }}
          tags: |
            ${{ inputs.VERSION }}
            latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@94f8f8c2eec4bc3f1d78c1755580779804cb87b2 # v6.0.1
        with:
          context: ./
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            "SCOPE=@nezuchan/${{ matrix.scope }}"
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          no-cache: ${{ inputs.NO_CACHE == true }}
